#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any


def canonical_json(obj: Any) -> bytes:
    return json.dumps(
        obj,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")


def sha256_json(obj: Any) -> str:
    return "sha256:" + hashlib.sha256(canonical_json(obj)).hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Create or refresh a draft NCS paper evidence pack."
    )
    parser.add_argument("pack", type=Path, help="Pack directory")
    args = parser.parse_args()

    pack = args.pack
    pack.mkdir(parents=True, exist_ok=True)

    manifest_path = pack / "manifest.json"
    if not manifest_path.exists():
        example = pack / "manifest.example.json"
        if example.exists():
            manifest_path.write_text(example.read_text(encoding="utf-8"), encoding="utf-8")
        else:
            manifest_path.write_text(
                json.dumps({"pack_id": pack.name}, indent=2),
                encoding="utf-8",
            )

    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

    receipt = {
        "pack_id": manifest.get("pack_id"),
        "profile": manifest.get("profile"),
        "verdict": "PASS",
        "manifest_digest": sha256_json(manifest),
        "note": (
            "Draft placeholder receipt generated by make_ncs_pack.py; "
            "replace with validator-generated receipt."
        ),
    }

    summary = {
        "pack_id": manifest.get("pack_id"),
        "domain": manifest.get("task", {}).get("domain"),
        "workflow_name": manifest.get("task", {}).get("workflow_name"),
        "expected_verdict": manifest.get("expected", {}).get("verdict", "PASS"),
        "receipt_digest": sha256_json(receipt),
        "note": "Placeholder summary for manuscript scaffold only.",
    }

    (pack / "receipt.json").write_text(
        json.dumps(receipt, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    (pack / "summary.json").write_text(
        json.dumps(summary, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    (pack / "expected_digest.txt").write_text(
        summary["receipt_digest"] + "\n",
        encoding="utf-8",
    )

    print(f"Wrote {pack / 'manifest.json'}")
    print(f"Wrote {pack / 'receipt.json'}")
    print(f"Wrote {pack / 'summary.json'}")
    print(f"Wrote {pack / 'expected_digest.txt'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
